ParkingSystemProject/ParkingSystem/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using ParkingSystem.Data.Models;
using ParkingSystem.Data;

namespace ParkingSystem.Controllers
{
    public class CarController : Controller
    {
        [HttpPost]
        public IActionResult AddCar(Car car)
        {
            DataAccess.Cars.Add(car);
            return Redirect("/");
        }
        [HttpPost]
        public IActionResult DeleteCar(string plateNumber)
        {
            var car = DataAccess.Cars.FirstOrDefault(x => x.PlateNumber == plateNumber);
            DataAccess.Cars.Remove(car);
            return Redirect("/");
        }
    }
}

ParkingSystemProject/ParkingSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ParkingSystem.Data;

namespace ParkingSystem.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(DataAccess.Cars);
        }
    }
}

ParkingSystemProject/ParkingSystem/Views/Home/Index.cshtml
@model IEnumerable<Car>

@{
    ViewData["Title"] = "Parking System";
}

<div class="text-center">
    <h1 class="display-7">Parking system</h1>
</div>


<div class="row">
    <div class="col-md-4">
        <h3>Parking System</h3>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">
                        Car Make
                    </th>
                    <th scope="col">
                        Plate Number
                    </th>
                    <th scope="col">

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CarMake)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlateNumber)
                        </td>
                        <td>
                            <form method="post" asp-controller="Car" asp-action="DeleteCar">
                                <input type="hidden" name="plateNumber" asp-for="@item.PlateNumber" />
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @using (Html.BeginForm("AddCar", "Car", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <legend>New Car</legend>
            <div class="form-group">
                <label for="name" class="col-lg-2 control-label">Make</label>
                <div class="col-lg-10">
                    <input type="text" autofocus="autofocus" name="carMake" title="CarMake" class="form-control" id="name" />
                </div>
            </div>
            <div class="form-group">
                <label for="number" class="col-lg-2 control-label">Plate #</label>
                <div class="col-lg-10">
                    <input type="text" autofocus="autofocus" name="plateNumber" title="PlateNumber" class="form-control" id="number" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 mt-2 col-lg-offset-2">
                    <button type="submit" class="btn btn-success">Add</button>
                </div>
            </div>
        }
    </div>
</div>

ParkingSystemProject/ParkingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParkingSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ParkingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color: #022E1E;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:white; ">ParkingSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - ParkingSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>